variables:
  TFStateContainer: "applz-states"
  AppInfraProjectName: "ESLZ Infrastructure Application Landing Zones"

  stage1ALZName: "aen-<<env_shortname>>-<<app_name>>-sub001-<<loc_shortname>> example aen-np-aXXXX-sub001-ae"
  stage1AppName: ${{ split(variables.stage1ALZName, '-')[2] }}
  stage1AppNameEnv: <<app_name>>_np
  stage1Env: ${{ split(variables.stage1AppNameEnv, '_')[1] }}
  stage1Region: "<<app_region>>"
  stage1TFStateSubscriptionID: "5b647192-86e7-43e2-a272-0e6358f16130"
  stage1TFStateResourceGroup: "aen-npae-mgmt-states"
  stage1TFStateStorageAccount: "aennpaemgmtsastates"
  ${{ if endsWith( variables['Build.DefinitionName'], '-Pool' ) }}:
    stage1SubId: "d8722324-0c79-4c64-ae39-9ff4c28e25c6"
    stage1additionalParameters: '-var env_specific_config="$(stage1AppName)/alz_variables_$(stage1Env)_$(stage1Region).json" -var env_global_config="$(stage1AppName)/alz_variables_$(stage1Env)_global.json" -var splunk_targeturi="10.75.1.22:8089" -var splunk_network=EPIC -var splunk_env=NPRD -var splunk_appname=LZ -var newrelickey="$(aztec-azure-np-infrastructure)" -var newrelic_proxy="proxy.nexus.telstra.com.au:8080" -var ado_server_url="$(System.CollectionUri)" -var azuredevops_project="$(AppInfraProjectName)" -var ado_pat_token="$(System.AccessToken)"'
  ${{ else }}:
    stage1SubId: "<<app_subscription>>"
    stage1additionalParameters: '-var env_specific_config=alz_variables_$(stage1Env)_$(stage1Region).json -var env_global_config="alz_variables_$(stage1Env)_global.json" -var env_specific_nsg_rules=nsg_rules_$(stage1Env)_$(stage1Region).csv -var env_specific_route_rules=route_rules_$(stage1Env)_$(stage1Region).csv'

  ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),eq(variables['Build.Reason'], 'IndividualCI'),eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.SourceBranch'], '')) }}:
    stage2ALZName: "aen-<<env_shortname>>-<<app_name>>-sub001-<<loc_shortname>> example aen-pd-aXXXX-sub001-ae"
    stage2AppName: ${{ split(variables.stage2ALZName, '-')[2] }}
    stage2AppNameEnv: <<app_name>>_prod
    stage2Env: ${{ split(variables.stage2AppNameEnv, '_')[1] }}
    stage2Region: "<<app_region>>"
    stage2TFStateSubscriptionID: "1cc42379-e59f-477f-8aa6-dcf005f15940"
    stage2TFStateResourceGroup: "aen-pdae-mgmt-states"
    stage2TFStateStorageAccount: "aenpdaemgmtsastates"
    ${{ if endsWith( variables['Build.DefinitionName'], '-Pool' ) }}:
      stage2SubId: "03af178c-b8d7-40c4-abcf-9458521534bc"
      stage2additionalParameters: '-var env_specific_config="$(stage2AppName)/alz_variables_$(stage2Env)_$(stage2Region).json" -var env_global_config="$(stage2AppName)/alz_variables_$(stage2Env)_global.json" -var splunk_targeturi="10.75.1.22:8089" -var splunk_network=EPIC -var splunk_env=PRD -var splunk_appname=LZ -var newrelickey="$(aztec-azure-pr-infrastructure)" -var newrelic_proxy="proxy.nexus.telstra.com.au:8080" -var ado_server_url="$(System.CollectionUri)" -var azuredevops_project="$(AppInfraProjectName)" -var ado_pat_token="$(System.AccessToken)"'
    ${{ else }}:
      stage2SubId: "<<app_subscription>>"
      stage2additionalParameters: '-var env_specific_config=alz_variables_$(stage2Env)_$(stage2Region).json -var env_global_config="alz_variables_$(stage2Env)_global.json" -var env_specific_nsg_rules=nsg_rules_$(stage2Env)_$(stage2Region).csv -var env_specific_route_rules=route_rules_$(stage2Env)_$(stage2Region).csv'
